name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # For staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 Host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 13.60.199.116 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@13.60.199.116 << 'EOF'
          cd /var/www/dev-app  # Change this to /var/www/stage-app for staging
          git pull origin dev  # Or pull from main for staging
          docker-compose down  # Stop running containers (optional)
          docker-compose up -d  # Deploy new version (optional)
          EOF
